# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba75e095a9070793374067b56883f388b03727be6670fe71f77fcc55ccb5f0938ef08c8c75b89bb857ae6874c7a82d02cb4b09825d1f3d05c62231398d92396e

test:
  secret_key_base: ff684b491a71da8f3c938d20cc7af209fdfb6129fd0c64cebefb61bc60a8be178d8e287799a96a531c9bf6abdb96e9b13553f4d7502a2fa0af8748b429ed10c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
